Repository xapi-project/xen-api, pull requests merged in 2018-03, with the labels that each got.

#3470 [From REQ-477] Cherry-pick addition of iSCSI IQN and multipathing changes
  ocaml/idl/datamodel_host.ml
  ocaml/tests/suite.ml
  ocaml/tests/test_common.ml
  ocaml/tests/test_host_helpers.ml
  ocaml/tests/test_sm_features.ml
  ocaml/xapi/message_forwarding.ml
  ocaml/xapi/records.ml
  ocaml/xapi/smint.ml
  ocaml/xapi/xapi.ml
  ocaml/xapi/xapi_globs.ml
  ocaml/xapi/xapi_host.ml
  ocaml/xapi/xapi_host.mli
  ocaml/xapi/xapi_host_helpers.ml
  ocaml/xapi/xapi_host_helpers.mli
  scripts/xe-set-iscsi-iqn
Labels: reviewed

#3473 [From REQ-477] Cherry-pick of shutdown changes
  ocaml/idl/datamodel_host.ml
  ocaml/xapi-client/jbuild
  ocaml/xapi-client/tasks.ml
  ocaml/xapi-client/tasks.mli
  ocaml/xapi/cli_frontend.ml
  ocaml/xapi/cli_operations.ml
  ocaml/xapi/message_forwarding.ml
  ocaml/xapi/vm_evacuation.ml
  ocaml/xapi/xapi_ha.ml
  ocaml/xapi/xapi_ha.mli
  ocaml/xapi/xapi_host.ml
  ocaml/xapi/xapi_host.mli
  ocaml/xapi/xapi_host_helpers.ml
  ocaml/xapi/xapi_host_helpers.mli
  ocaml/xapi/xapi_pbd.ml
  ocaml/xapi/xha_scripts.ml
  scripts/xapi-domains.service
  xapi-client.opam
Labels: reviewed

#3482 [477 merge review draft] GFS2 feature branch
  ocaml/idl/datamodel.ml
  ocaml/idl/datamodel_cluster.ml
  ocaml/idl/datamodel_cluster_host.ml
  ocaml/idl/datamodel_common.ml
  ocaml/idl/datamodel_errors.ml
  ocaml/idl/datamodel_pool.ml
  ocaml/idl/datamodel_types.ml
  ocaml/idl/jbuild
  ocaml/quicktest/quicktest.ml
  ocaml/quicktest/quicktest_cbt.ml
  ocaml/quicktest/quicktest_storage.ml
  ocaml/tests/suite.ml
  ocaml/tests/suite_alcotest.ml
  ocaml/tests/test_cluster.ml
  ocaml/tests/test_cluster_host.ml
  ocaml/tests/test_clustering.ml
  ocaml/tests/test_clustering_allowed_operations.ml
  ocaml/tests/test_common.ml
  ocaml/xapi-consts/api_errors.ml
  ocaml/xapi-consts/constants.ml
  ocaml/xapi-types/features.ml
  ocaml/xapi-types/features.mli
  ocaml/xapi/api_server.ml
  ocaml/xapi/cancel_tasks.ml
  ocaml/xapi/cli_frontend.ml
  ocaml/xapi/cli_operations.ml
  ocaml/xapi/context.ml
  ocaml/xapi/context.mli
  ocaml/xapi/create_storage.ml
  ocaml/xapi/jbuild
  ocaml/xapi/message_forwarding.ml
  ocaml/xapi/record_util.ml
  ocaml/xapi/records.ml
  ocaml/xapi/xapi.ml
  ocaml/xapi/xapi_cluster.ml
  ocaml/xapi/xapi_cluster.mli
  ocaml/xapi/xapi_cluster_helpers.ml
  ocaml/xapi/xapi_cluster_host.ml
  ocaml/xapi/xapi_cluster_host.mli
  ocaml/xapi/xapi_cluster_host_helpers.ml
  ocaml/xapi/xapi_clustering.ml
  ocaml/xapi/xapi_globs.ml
  ocaml/xapi/xapi_host_helpers.ml
  ocaml/xapi/xapi_pbd.ml
  ocaml/xapi/xapi_pool.ml
  ocaml/xapi/xapi_pool_helpers.ml
  ocaml/xapi/xapi_sr.ml
  ocaml/xapi/xapi_vm_lifecycle.ml
  ocaml/xe-cli/bash-completion
  scripts/Makefile
  scripts/examples/python/shutdown.py
  scripts/xe-toolstack-restart
Labels: feature review

#3492 CP-27272: Fix for VM without SR-IOV VIFs start failed
  ocaml/tests/test_vm_helpers.ml
  ocaml/xapi/xapi_network_sriov_helpers.ml
  ocaml/xapi/xapi_vm_helpers.ml
Labels: updated
