Repository xapi-project/xen-api, pull requests merged in 2024-03, with the labels that each got.

#5480 py2->py3: hfx_filename
  .codecov.yml
  .github/workflows/main.yml
  pyproject.toml
  python3/Makefile
  python3/bin/hfx_filename
  python3/unittest/import_file.py
  python3/unittest/test_hfx_filename.py
  scripts/Makefile
Labels: py3-update

#5482 Sync feature/py3 branch with master
  .github/workflows/main.yml
  doc/content/xapi-guard/_index.md
  ocaml/sdk-gen/csharp/templates/Message2.mustache
  ocaml/xapi-cli-protocol/cli_protocol.ml
  ocaml/xapi-cli-server/cli_frontend.ml
  ocaml/xapi-cli-server/cli_operations.ml
  ocaml/xapi-guard/lib/disk_cache.ml
  ocaml/xapi-guard/lib/disk_cache.mli
  ocaml/xapi-guard/lib/dune
  ocaml/xapi-guard/lib/lwt_bounded_stream.ml
  ocaml/xapi-guard/lib/lwt_bounded_stream.mli
  ocaml/xapi-guard/lib/server_interface.ml
  ocaml/xapi-guard/lib/types.ml
  ocaml/xapi-guard/lib/types.mli
  ocaml/xapi-guard/src/dune
  ocaml/xapi-guard/src/main.ml
  ocaml/xapi-guard/test/cache_test.ml
  ocaml/xapi-guard/test/cache_test.mli
  ocaml/xapi-guard/test/dune
  ocaml/xapi-guard/test/xapi_guard_test.ml
  ocaml/xapi/xapi_fist.ml
  ocaml/xe-cli/newcli.ml
  quality-gate.sh
Labels: py3-update

#5433 [ASAP] CP-47431: Use un-patched Json.NET in C# SDK and package SDK in releases. Update PS SDK to use NuGet reference to XenServer.NET
  .github/workflows/cleanup-xapi-environment/action.yml
  .github/workflows/generate-and-build-sdks.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/setup-xapi-environment/action.yml
  Makefile
  ocaml/sdk-gen/csharp/FriendlyErrorNames.resx
  ocaml/sdk-gen/csharp/autogen/.gitignore
  ocaml/sdk-gen/csharp/autogen/README.md
  ocaml/sdk-gen/csharp/autogen/dune
  ocaml/sdk-gen/csharp/autogen/src/Failure.cs
  ocaml/sdk-gen/csharp/autogen/src/README-NuGet.md
  ocaml/sdk-gen/csharp/dune
  ocaml/sdk-gen/csharp/friendly_error_names.ml
  ocaml/sdk-gen/csharp/templates/FriendlyErrorNames.Designer.mustache
  ocaml/sdk-gen/csharp/templates/XenServer.csproj.mustache
  ocaml/sdk-gen/powershell/README.dist
  ocaml/sdk-gen/powershell/README_51.dist
  ocaml/sdk-gen/powershell/autogen/.gitignore
  ocaml/sdk-gen/powershell/autogen/README.md
  ocaml/sdk-gen/powershell/autogen/README_51.md
  ocaml/sdk-gen/powershell/autogen/XenServerPSModule.psd1
  ocaml/sdk-gen/powershell/autogen/dune
  ocaml/sdk-gen/powershell/autogen/src/XenServerPowerShell.csproj
  ocaml/sdk-gen/powershell/gen_powershell_binding.ml
Labels: reviewed

#5496 GitHub Actions: Update actions/checkout to v4 to fix Node 16 warnings
  .github/workflows/1.249-lcm.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/generate-and-build-sdks.yml
  .github/workflows/hugo.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI-only, warning fixes

#5499 GitHub Actions: Node 16 warning fixes: update setup-dotnet to v4
  .github/workflows/generate-and-build-sdks.yml
Labels: CI-only, warning fixes

#5338 [OIL] Split the API reference markdown into smaller files and use templates to generate it.
  Makefile
  ocaml/doc/basics.md
  ocaml/doc/vm-lifecycle.md
  ocaml/doc/wire-protocol.md
  ocaml/idl/autogen/api-ref-autogen.md
  ocaml/idl/autogen/dune
  ocaml/idl/datamodel.ml
  ocaml/idl/datamodel_certificate.ml
  ocaml/idl/datamodel_errors.ml
  ocaml/idl/datamodel_host.ml
  ocaml/idl/datamodel_main.ml
  ocaml/idl/dune
  ocaml/idl/markdown_backend.ml
  ocaml/idl/templates/api_errors.mustache
  ocaml/idl/templates/class.mustache
  ocaml/idl/templates/classes.mustache
  ocaml/idl/templates/relationships.mustache
  ocaml/idl/templates/toc.mustache
  ocaml/idl/templates/types.mustache
Labels: reviewed

#5424 CP-47555 Porting usb_scan.py to python3
  .github/workflows/main.yml
  pyproject.toml
  python3/Makefile
  python3/libexec/usb_scan.py
  python3/unittest/import_file.py
  python3/unittest/test_hfx_filename.py
  python3/unittest/test_usb_scan.py
  scripts/Makefile
Labels: py3-update

#5490 py2->py3: nbd_client_manager.py
  pyproject.toml
  python3/Makefile
  python3/libexec/nbd_client_manager.py
  python3/unittest/test_nbd_client_manager.py
  scripts/Makefile
Labels: py3-update

#5303 [OIL] Moved some more generation code to templates.
  ocaml/sdk-gen/c/gen_c_binding.ml
  ocaml/sdk-gen/c/templates/xen_enum.c.mustache
  ocaml/sdk-gen/c/templates/xen_enum.h.mustache
  ocaml/sdk-gen/c/templates/xen_enum_internal.h.mustache
  ocaml/sdk-gen/csharp/autogen/src/XenServer.csproj
  ocaml/sdk-gen/csharp/gen_csharp_binding.ml
  ocaml/sdk-gen/csharp/templates/Maps.mustache
  ocaml/sdk-gen/csharp/templates/Relation.mustache
  ocaml/sdk-gen/powershell/gen_powershell_binding.ml
  ocaml/sdk-gen/powershell/templates/ConvertTo-XenRef.mustache
  ocaml/sdk-gen/powershell/templates/HttpAction.mustache
Labels: reviewed

#5517 CA-390109: Use `$PROFILE` path to store and read known cert list
  ocaml/sdk-gen/powershell/autogen/Initialize-Environment.ps1
  ocaml/sdk-gen/powershell/autogen/src/CommonCmdletFunctions.cs
  ocaml/sdk-gen/powershell/autogen/src/Connect-XenServer.cs
  ocaml/sdk-gen/powershell/autogen/src/XenServerPowerShell.csproj
Labels: updated

#5511 CP-48466 Fix ci warnings for usb_scan.py
  pyproject.toml
  python3/libexec/usb_scan.py
  python3/unittest/test_usb_scan.py
Labels: py3-update

#5527 CP-47653: py2->py3 for perfmon
  .codecov.yml
  .github/workflows/main.yml
  pyproject.toml
  python3/Makefile
  python3/bin/perfmon
  python3/unittest/test_nbd_client_manager.py
  python3/unittest/test_perfmon.py
  scripts/Makefile
  scripts/perfmon
  scripts/plugins/perfmon
Labels: py3-update
