Repository xapi-project/xen-api, pull requests merged in 2024-04, with the labels that each got.

#5547 Port of "Fix C SDK build on Fedora39" to `master`
  Makefile
  ocaml/sdk-gen/c/autogen/src/xen_common.c
  ocaml/sdk-gen/c/gen_c_binding.ml
Labels: please review

#5404 CP-47033: Make message switch concurrent processing optional
  ocaml/message-switch/async/protocol_async.ml
  ocaml/message-switch/core/dune
  ocaml/message-switch/core/make.ml
  ocaml/message-switch/core/s.ml
  ocaml/message-switch/core_test/async/server_async_main.ml
  ocaml/message-switch/core_test/basic-rpc-test.sh
  ocaml/message-switch/core_test/concur-rpc-test.sh
  ocaml/message-switch/core_test/dune
  ocaml/message-switch/core_test/lwt/server_main.ml
  ocaml/message-switch/lwt/protocol_lwt.ml
  ocaml/message-switch/switch/switch_main.ml
  ocaml/message-switch/unix/protocol_unix.ml
Labels: reviewed

#5362 Add test for lock implementation in message_switch
  ocaml/message-switch/async/protocol_async.ml
  ocaml/message-switch/async/protocol_async.mli
  ocaml/message-switch/core/dune
  ocaml/message-switch/core/mtest.ml
  ocaml/message-switch/core/s.ml
  ocaml/message-switch/core_test/dune
  ocaml/message-switch/core_test/lock_test_async.ml
  ocaml/message-switch/core_test/lock_test_lwt.ml
  ocaml/message-switch/lwt/protocol_lwt.ml
  ocaml/message-switch/lwt/protocol_lwt.mli
  quality-gate.sh
Labels: please review

#5587 Exposed system_list_methods in C# SDK. Correction to github workflow.
  .github/workflows/generate-and-build-sdks.yml
  ocaml/doc/basics.md
  ocaml/doc/vm-lifecycle.md
  ocaml/doc/wire-protocol.md
  ocaml/idl/autogen/api-ref-autogen.md
  ocaml/sdk-gen/csharp/autogen/src/Session.cs
  ocaml/sdk-gen/csharp/templates/JsonRpcClient.mustache
Labels: sdk-members-only
