Repository xapi-project/xen-api, pull requests merged in 2024-07, with the labels that each got.

#5796 CP-49906: mv `scripts/plugins/extauth-hook*` to `python3/plugins`
  python3/Makefile
  python3/plugins/extauth-hook
  python3/plugins/extauth-hook-AD.py
  python3/plugins/extauth_hook_ad.py
  python3/plugins/test_extauth_hook_AD.py
  scripts/Makefile
Labels: updated, py3-update

#5795 CP-50100: `backup-sr-metadata,restore-sr-metadata`: `2to3`, fix `pytype`, `pyright`
  pyproject.toml
  python3/stubs/XenAPI.pyi
  scripts/backup-sr-metadata.py
  scripts/restore-sr-metadata.py
Labels: updated, py3-update

#5812 `python3/plugins/test_extauth_hook_AD.py`: Fix logging in `run_cmd()`
  python3/plugins/extauth-hook-AD.py
  python3/plugins/test_extauth_hook_AD.py
Labels: py3-bugfix, py3-update, Move to python3 directory

#5818 CP-49928: Moved static-vdis from scripts/ to python3/bin directory
  python3/Makefile
  python3/bin/static-vdis
  python3/tests/test_static_vdis.py
  scripts/Makefile
Labels: Move to python3 directory

#5836 Py3: Cleanup `test_mail-alarm.py` to use python3 test helpers an move it
  python3/tests/test_mail-alarm.py
Labels: py3-update

#5554 [OIL] Templatization of PS Remove-Xen* cmdlets. Refactoring of HTTP_actions.mustache
  ocaml/sdk-gen/csharp/friendly_error_names.ml
  ocaml/sdk-gen/csharp/gen_csharp_binding.ml
  ocaml/sdk-gen/csharp/templates/HTTP_actions.mustache
  ocaml/sdk-gen/powershell/gen_powershell_binding.ml
  ocaml/sdk-gen/powershell/templates/Remove-XenObject.mustache
Labels: updated, sdk-members-only

#5813 Update the `mypy` config for `python3/` (found #5812 with it)`
  pyproject.toml
Labels: py3-bugfix, py3-update, Move to python3 directory

#5845 `plugins/extauth-hook-AD.py`: Fix 'Stray abstractmethod' pytype warning
  python3/plugins/extauth-hook-AD.py
Labels: Py3: Cleanup static analysis comments, Modernise Code

#5847 `test_extauth_hook_ad.py`: Modernise testee import to not need a symlink
  python3/plugins/extauth_hook_ad.py
  python3/plugins/test_extauth_hook_AD.py
  python3/tests/import_helper.py
Labels: Modernize Python tests

#5828 Cleanup obsolete `PBIS` support (removed in XS8) from extauth-hook-AD.py
  python3/plugins/extauth-hook-AD.py
  python3/plugins/test_extauth_hook_AD.py
Labels: updated, Remove obsolete code

#5854 storage-api: `__init__.py`: Use `is_str()` to check for string type
  .github/workflows/other.yml
  ocaml/xapi-storage/python/xapi/__init__.py
  ocaml/xapi-storage/python/xapi/storage/api/datapath.py
  ocaml/xapi-storage/python/xapi/storage/api/plugin.py
  ocaml/xapi-storage/python/xapi/storage/api/test_datapath.py
  ocaml/xapi-storage/python/xapi/storage/api/volume.py
  pyproject.toml
Labels: updated, Enhancement, Modernize Python tests, Modernise Code, Make generated Python code more readable

#5873 Remove the no longer used legacy baseline SMAPIv3 scripts and tests (api.v5 is the current SMAPIv3 version)
  ocaml/xapi-storage-script/main.ml
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/Plugin.Query
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/Plugin.diagnostics
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/SR.attach
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/SR.create
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/SR.detach
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/SR.ls
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/SR.stat
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/Volume.create
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/Volume.destroy
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/Volume.stat
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/plugin.py
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/sr.py
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummy/volume.py
  ocaml/xapi-storage-script/test/volume/org.xen.xapi.storage.dummyv5/plugin.py
  ocaml/xapi-storage/python/xapi/storage/api/datapath.py
  ocaml/xapi-storage/python/xapi/storage/api/plugin.py
  ocaml/xapi-storage/python/xapi/storage/api/test_datapath.py
  ocaml/xapi-storage/python/xapi/storage/api/volume.py
Labels: py3-update, Remove obsolete code

#5867 py3: Config updates for removing and deprecating Python2 support
  .github/workflows/other.yml
  .pre-commit-config.yaml
  pyproject.toml
  scripts/examples/python/setup.cfg
Labels: py3-update
