Repository xapi-project/xen-api, pull requests merged in 2024-08, with the labels that each got.

#5869 IH-662: Get rid of non-threadsafe Re.Str usage in XAPI
  ocaml/tests/dune
  ocaml/tests/test_xapi_helpers.ml
  ocaml/xapi/helpers.ml
Labels: reviewed

#5918 Plugin `openvswitch-config-update`: fix python2ism in python3 migration
  scripts/plugins/openvswitch-config-update
Labels: py3-bugfix

#5921 `xenopsd`: Fix `pytype` warning on `get_words`: Name `string` is not defined
  ocaml/xenopsd/scripts/common.py
  ocaml/xenopsd/scripts/test_common_class_vif.py
Labels: Fix pytype warnings

#5923 Fix pytype / delete xenopsd/qemu-vif-script (qemu backend was removed in 2017)
  Makefile
  ocaml/xapi-storage/python/examples/datapath/loop+blkback/datapath.py
  ocaml/xenopsd/scripts/common.py
  ocaml/xenopsd/scripts/make-custom-xenopsd.conf
  ocaml/xenopsd/scripts/qemu-vif-script
  ocaml/xenopsd/xenopsd.conf
  pyproject.toml
Labels: Remove obsolete code, Fix pytype warnings

#5938 CA-396751/py3: Test changes in `rrdd.API.update()`, fix `pyright`
  ocaml/xcp-rrdd/scripts/rrdd/test_api_wait_until_next_reading.py
  python3/stubs/xcp/cmd.pyi
  python3/stubs/xcp/compat.pyi
Labels: CI, Python tests(coverage), pyright analysis

#5946 Add temporary exception for deprecation of `xmlStringDecodeEntities`
  ocaml/sdk-gen/c/autogen/src/xen_common.c
Labels: sdk-members-only
